improve (?) mulle-bootstrap detection

diff --git a/mulle-build b/mulle-build
--- a/mulle-build
+++ b/mulle-build
@@ -30,7 +30,7 @@
 #   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 #   POSSIBILITY OF SUCH DAMAGE.
 
-MULLE_EXECUTABLE_VERSION="3.4.8" # mulle-build version
+MULLE_EXECUTABLE_VERSION="3.4.9" # mulle-build version
 
 MULLE_BOOTSTRAP_MIN_MAJOR="3"
 MULLE_BOOTSTRAP_MIN_MINOR="4"
@@ -707,10 +707,18 @@ build_init()
    # look for mulle-bootstrap in the place where mulle-build is, they
    # belong together
 
+   set -x
+   echo "$PATH" >&2
+
    MULLE_BOOTSTRAP_EXE="`dirname -- "$0"`/mulle-bootstrap"
    if [ ! -x "${MULLE_BOOTSTRAP_EXE}" ]
    then
-      MULLE_BOOTSTRAP_EXE=mulle-bootstrap
+      MULLE_BOOTSTRAP_EXE="`command -v mulle-bootstrap`"
+      if [ ! -x "${MULLE_BOOTSTRAP_EXE}" ]
+      then
+         echo "mulle-bootstrap not installed in $PATH. Can't continue!" >&2
+         exit 1
+      fi
    fi
 
    local libexecpath
