add -install and other options for the benefit of windows

diff --git a/mulle-build b/mulle-build
--- a/mulle-build
+++ b/mulle-build
@@ -215,8 +215,14 @@ cmake_clean()
 {
    log_debug "cmake_clean" "$*"
 
-   log_verbose "Deleting \"${BUILD_DIR}/CMakeFiles\""
-   exekutor rm -rf "${BUILD_DIR}/CMakeFiles" 2> /dev/null
+   if [ -d "${BUILD_DIR}" ]
+   then
+      (
+         log_verbose "make clean in \"${BUILD_DIR}\""
+         exekutor cd "${BUILD_DIR}"
+         exekutor make clean 2> /dev/null
+      )
+   fi
 }
 
 
@@ -249,7 +255,7 @@ need_cmake_cache_clean()
 
 need_cmake_clean()
 {
-   if [ "${OPTION_NO_CLEAN}" = "YES" ]
+   if [ "${OPTION_CLEAN}" = "NO" ]
    then
       return 1
    fi
@@ -791,6 +797,9 @@ local_mode()
 }
 
 
+#
+# Xcode mode generates a xcodeproj from CMakeLists.txt
+#
 xcode_mode()
 {
    log_debug "xcode_mode" "$*"
@@ -1073,7 +1082,7 @@ run_test()
    then
       (
          exekutor cd "${testdir}"
-         TEST_PATH_PREFIX="${userrel}" eval_exekutor "./build-test.sh" "${BUILD_TEST_OPTIONS}" "$@"
+         TEST_PATH_PREFIX="${userrel}" eval_exekutor "./build-test.sh" ${BUILD_TEST_OPTIONS} "$@"
       ) || exit 1
    else
       if [ -f "${testdir}/build-test.sh" ]
@@ -1120,8 +1129,26 @@ run_test()
 
 build_init()
 {
+   #
+   # shell export commands with minimal
+   # trap setup
+   #
+   case "${1}" in
+      version)
+         echo "${MULLE_EXECUTABLE_VERSION}"
+         exit 0
+      ;;
+
+      minimum-bootstrap-version)
+         echo "${MULLE_BOOTSTRAP_MIN_MAJOR}.${MULLE_BOOTSTRAP_MIN_MINOR}.0"
+         exit 0
+      ;;
+   esac
+
+   #
    # look for mulle-bootstrap in the place where mulle-build is, they
    # belong together
+   #
 
    MULLE_BOOTSTRAP_EXE="`dirname -- "$0"`/mulle-bootstrap"
    if [ ! -x "${MULLE_BOOTSTRAP_EXE}" ]
@@ -1139,26 +1166,9 @@ build_init()
    libexecpath="`${MULLE_BOOTSTRAP_EXE} library-path`"
    if [ -z "${libexecpath}" ]
    then
-      echo "mulle-bootstrap not installed ? Can't continue" >&2
+      echo "mulle-bootstrap does not return library-path. Can't continue" >&2
       exit 1
    fi
-
-   #
-   # shell export commands with minimal
-   # trap setup
-   #
-   case "${1}" in
-      version)
-         echo "${MULLE_EXECUTABLE_VERSION}"
-         exit 0
-      ;;
-
-      minimum-bootstrap-version)
-         echo "${MULLE_BOOTSTRAP_MIN_MAJOR}.${MULLE_BOOTSTRAP_MIN_MINOR}.0"
-         exit 0
-      ;;
-   esac
-
 
    PATH="${libexecpath}:$PATH"
    export PATH
@@ -1184,6 +1194,13 @@ main()
    #
    command="`echo "${MULLE_EXECUTABLE}" | cut -d- -f2`"
 
+   case "$1" in
+      -analyze|-build|-install|-clean|-git|-status|-tag|-test|-xcode)
+         command="${1:1}"
+         shift
+      ;;
+   esac
+   #
    # technical flags
    local MULLE_FLAG_EXEKUTOR_DRY_RUN="NO"
    local MULLE_FLAG_LOG_CACHE="NO"
@@ -1204,11 +1221,12 @@ main()
    local BOOTSTRAP_OPTIONS=
    local BUILD_DIR="${BUILD_DIR:-build}"
    local TEST_OPTIONS=
+   local BUILD_TEST_OPTIONS=
    local XCODEBUILD_DIR="${XCODEBUILD_DIR:-build-xcode.d}"
 
    local OPTION_BUILD_DEPENDENCIES="YES"
    local OPTION_INSTALL="NO"
-   local OPTION_NO_CLEAN="NO"
+   local OPTION_CLEAN="YES"
    local OPTION_URL_INSTALL_DEPENDENCIES="YES"
    local OPTION_LOCAL_INSTALL_DEPENDENCIES="NO"
    local OPTION_OPEN_XCODE="NO"
@@ -1252,9 +1270,10 @@ main()
          BOOTSTRAP_FLAGS="`concat "${BOOTSTRAP_FLAGS}" "$1"`"
 
          case "$1" in
-            -v*|-V*|--debug)
+            -t|-v*|-V*|--debug)
                BUILD_TEST_OPTIONS="`concat "${BUILD_TEST_OPTIONS}" $1`"
                TEST_OPTIONS="`concat "${TEST_OPTIONS}" $1`"
+            ;;
          esac
 
          shift
@@ -1283,8 +1302,8 @@ main()
 
          -d|--debug)
             DEBUG="YES"
-            BUILD_TEST_OPTIONS="`concat "${BUILD_TEST_OPTIONS}" "--debug"`"
-            TEST_OPTIONS="`concat "${TEST_OPTIONS}" "--debug"`"
+            BUILD_TEST_OPTIONS="`concat "${BUILD_TEST_OPTIONS}" "$1"`"
+            TEST_OPTIONS="`concat "${TEST_OPTIONS}" "$1"`"
          ;;
 
          --dump-environment)
@@ -1355,7 +1374,9 @@ main()
          ;;
 
          --no-clean)
-            OPTION_NO_CLEAN="YES"
+            TEST_OPTIONS="`concat "${TEST_OPTIONS}" "$1"`"
+            BUILD_TEST_OPTIONS="`concat "${BUILD_TEST_OPTIONS}" "$1"`"
+            OPTION_CLEAN="NO"
          ;;
 
          --install)
