* adapt to new mulle-bashfunctions 1.3

diff --git a/mulle-craft b/mulle-craft
--- a/mulle-craft
+++ b/mulle-craft
@@ -29,17 +29,10 @@
 #   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 #   POSSIBILITY OF SUCH DAMAGE.
 #
-if [ "${TRACE}" = "YES" ]
-then
-   set -x
-fi
+[ "${TRACE}" = "YES" ] && set -x && : "$0" "$@"
 
 
-MULLE_EXECUTABLE_VERSION_MAJOR=0
-MULLE_EXECUTABLE_VERSION_MINOR=1
-MULLE_EXECUTABLE_VERSION_PATCH=1
-
-MULLE_EXECUTABLE_VERSION="${MULLE_EXECUTABLE_VERSION_MAJOR}.${MULLE_EXECUTABLE_VERSION_MINOR}.${MULLE_EXECUTABLE_VERSION_PATCH}"
+MULLE_EXECUTABLE_VERSION=0.2.0
 
 
 trap_fail()
@@ -85,83 +78,6 @@ EOF
    fi
 
    exit 1
-}
-
-
-#
-# stolen from:
-# http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
-# ----
-#
-_prepend_path_if_relative()
-{
-   case "$2" in
-      /*)
-         echo "$2"
-      ;;
-      *)
-         echo "$1/$2"
-      ;;
-   esac
-}
-
-
-resolve_symlinks()
-{
-   local dir_context
-   local linkpath
-
-   if linkpath="`readlink "$1"`"
-   then
-      dir_context=`dirname -- "$1"`
-      resolve_symlinks "`_prepend_path_if_relative "${dir_context}" "${linkpath}"`"
-   else
-      echo "$1"
-   fi
-}
-
-
-build_libexec_path()
-{
-   local executablepath="$1"
-
-   local exedir
-   local exedirpath
-   local prefix
-   local libexecpath
-
-   case "${executablepath}" in
-      \.*|/*|~*)
-      ;;
-
-      *)
-         executablepath="`command -v "${executablepath}"`"
-      ;;
-   esac
-
-   executablepath="`resolve_symlinks "${executablepath}"`"
-   exedirpath="`dirname "${executablepath}"`"
-   prefix="`dirname "${exedirpath}"`"
-   libexecpath="${prefix}/libexec/mulle-craft"
-
-   if [ ! -x "${libexecpath}/mulle-craft-execute.sh" ]
-   then
-      libexecpath="${exedirpath}/src"
-   fi
-
-   case "$libexecpath" in
-      /*|~*)
-      ;;
-
-      *)
-         libexecpath="$PWD/$libexecpath"
-      ;;
-   esac
-
-   if [ -x "${libexecpath}/mulle-craft-execute.sh" ]
-   then
-      echo "${libexecpath}"
-   fi
 }
 
 
@@ -288,6 +204,9 @@ main()
       ;;
    esac
 
+   DEPENDENCIES_DIR="${DEPENDENCIES_DIR:-${MULLE_VIRTUAL_ROOT}/dependencies}"
+   ADDICTIONS_DIR="${ADDICTIONS_DIR:-${MULLE_VIRTUAL_ROOT}/addictions}"
+
    local cmd
 
    cmd="$1"
@@ -302,7 +221,7 @@ main()
    #
    if [ -z "${cmd}" ]
    then
-      cmd="`cat .mulle-craft/default 2> /dev/null`"
+      cmd="`cat .mulle-craft/etc/default 2> /dev/null`"
    fi
 
    case "${cmd:-all}" in
@@ -376,76 +295,50 @@ main()
 }
 
 
+########
+###
+### INIT
+###
 _init()
 {
-   #
-   # minimal setup exit
-   #
    if [ "$1" = "version" ]
    then
-      echo "${MULLE_EXECUTABLE_VERSION}"
+      echo "${MULLE_ENV_VERSION}"
       exit 0
    fi
 
-   MULLE_CRAFT_LIBEXEC_DIR="`build_libexec_path "$0"`"
-   if [ -z "${MULLE_CRAFT_LIBEXEC_DIR}" ]
-   then
-      echo "$0 fatal error: Could not find libexec ($PWD)" >&2
-      exit 1
-   fi
-
-   #
-   # minimal setup exit
-   #
-   #
-   # minimal setup exit
-   #
-   case "$1" in
-      "libexec-dir"|"library-path")
-         echo "${MULLE_CRAFT_LIBEXEC_DIR}"
-         exit 0
-      ;;
-   esac
-
-
    MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir 2> /dev/null`"
-   if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
-   then
-      if [ -z "`command -v "${executablepath}"`" ]
-      then
-          echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH (not installed ?)" >&2
-      else
-         echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
-      fi
+   [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ] && \
+      echo "mulle-bashfunctions-env not installed" >&2 && \
       exit 1
+
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" "minimal" || exit 1
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-path.sh" || exit 1
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-file.sh" || exit 1
+
+   local _libexec_dir
+
+   _get_libexec_dir "$0" "mulle-craft" "mulle-craft-execute.sh"
+
+   if [ -z "${_libexec_dir}" ]
+   then
+      fail "Fatal Error: Could not find libexec for ${MULLE_EXECUTABLE} ($PWD)"
+   fi
+   MULLE_CRAFT_LIBEXEC_DIR="${_libexec_dir}"
+
+   #
+   # minimal setup exit
+   #
+   if [ "$1" = "libexec-dir" ]
+   then
+      echo "${MULLE_CRAFT_LIBEXEC_DIR}"
+      exit 0
    fi
 
-   local failmsg
-
-   failmsg="failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
-
-      # shellcheck source=../mulle-bashfunctions/src/mulle-string.sh
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-string.sh"   || fail "${failmsg}"
-      # shellcheck source=../mulle-bashfunctions/src/mulle-logging.sh
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-logging.sh"  || fail "${failmsg}"
-      # shellcheck source=../mulle-bashfunctions/src/mulle-exekutor.sh
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-exekutor.sh" || fail "${failmsg}"
-      # shellcheck source=../mulle-bashfunctions/src/mulle-options.sh
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-options.sh"  || fail "${failmsg}"
-      # shellcheck source=../mulle-bashfunctions/src/mulle-path.sh
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-path.sh"     || fail "${failmsg}"
-      # shellcheck source=../mulle-bashfunctions/src/mulle-file.sh
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-file.sh"     || fail "${failmsg}"
-
-
-   #  set -e # more pain then gain in the end
-   #  set -u # doesn't work with my style
-
-   trap trap_fail INT
    set -o pipefail
-
-   MULLE_ARGUMENTS="$*"
 }
+
+
 
 _init "$@" # needs params
 main "$@"
