allow to set build-dir from commandline try to clean cmake if CMake files changed

diff --git a/mulle-build b/mulle-build
--- a/mulle-build
+++ b/mulle-build
@@ -30,7 +30,7 @@
 #   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 #   POSSIBILITY OF SUCH DAMAGE.
 
-MULLE_EXECUTABLE_VERSION="3.7.0" # mulle-build version
+MULLE_EXECUTABLE_VERSION="3.8.0" # mulle-build version
 
 # 3.6 is ok
 MULLE_BOOTSTRAP_MIN_MAJOR="3"
@@ -98,16 +98,9 @@ EOF
 #
 # Local Mode
 #
-do_fetch_dependencies()
+_do_fetch_dependencies()
 {
-   log_debug "do_fetch_dependencies" "$*"
-
    local rval
-
-   if [ "${OPTION_SKIP_MULLE_BOOTSTRAP}" = "YES" ]
-   then
-      return
-   fi
 
    exekutor "${MULLE_BOOTSTRAP_EXE}" -s status
    rval="$?"
@@ -126,6 +119,40 @@ do_fetch_dependencies()
          log_verbose "Don't warn about scripts next build"
          exekutor "${MULLE_BOOTSTRAP_EXE}" config --on dont_warn_scripts
       fi
+   fi
+}
+
+do_fetch_dependencies()
+{
+   log_debug "do_fetch_dependencies" "$*"
+
+   local tmpdir
+   local git_mirror
+
+   if [ "${OPTION_SKIP_MULLE_BOOTSTRAP}" = "YES" ]
+   then
+      return
+   fi
+
+   #
+   # When installing and for homebrew, should always provide
+   # an at least temporary mirror
+   #
+   if [ "${OPTION_AUTO_MIRROR}" = "YES" ]
+   then
+      git_mirror="`exekutor mulle-bootstrap config "git_mirror"`"
+      if [ -z "${git_mirror}" ]
+      then
+         tmpdir="`mktemp -d "/tmp/mirror-XXXXXXXX"`"
+         exekutor mulle-bootstrap config "git_mirror" "${tmpdir}"
+      fi
+   fi
+
+   _do_fetch_dependencies "$@"
+
+   if [ -d "${tmpdir}" ]
+   then
+      exekutor rm -rf "${tmpdir}"
    fi
 }
 
@@ -175,15 +202,48 @@ do_install_dependencies()
 }
 
 
+cmake_cache_clean()
+{
+   log_debug "cmake_cache_clean" "$*"
+
+   log_verbose "Deleting \"${BUILD_DIR}/CMakeCache.txt\""
+   exekutor rm "${BUILD_DIR}/CMakeCache.txt" 2> /dev/null
+}
+
+
 cmake_clean()
 {
    log_debug "cmake_clean" "$*"
 
    log_verbose "Deleting \"${BUILD_DIR}/CMakeFiles\""
    exekutor rm -rf "${BUILD_DIR}/CMakeFiles" 2> /dev/null
+}
 
-   log_verbose "Deleting \"${BUILD_DIR}/CMakeCache.txt\""
-   exekutor rm "${BUILD_DIR}/CMakeCache.txt" 2> /dev/null
+
+need_cmake_cache_clean()
+{
+   local i
+   local old
+
+   if [ ! -f "${BUILD_DIR}/CMakeCache.txt" ]
+   then
+      return 1
+   fi
+
+   oldifs="${IFS}"
+   IFS="
+"
+   for i in `ls -1 CMake*.txt`
+   do
+      if [ "$i" -nt "${BUILD_DIR}/CMakeCache.txt" ]
+      then
+         return 0
+      fi
+   done
+
+   IFS="${OLDIFS}"
+
+   return 1
 }
 
 
@@ -194,7 +254,7 @@ need_cmake_clean()
       return 0
    fi
 
-   if [ ! -e "${BUILD_DIR}/CMakeFiles" ]
+   if [ ! -e "${BUILD_DIR}/CMakeFiles" ] # ???
    then
       return 0
    fi
@@ -284,7 +344,7 @@ _do_cmake()
       # CMAKE_FLAGS same as in mulle-bootstrap
       exekutor cd "${BUILD_DIR}"
 
-      if [ "${MULLE_TRACE}" = "YES" -o "${DUMP_ENVIRONMENT}" = "YES" ]
+      if [  "${MULLE_TRACE}" = "YES" -o "${DUMP_ENVIRONMENT}" = "YES" ]
       then
          log_verbose "Environment:"
          env | sort >&2
@@ -313,6 +373,12 @@ do_cmake()
 
    skip_build="${OPTION_OPTIMISTIC}"
 
+   if need_cmake_cache_clean
+   then
+      cmake_cache_clean
+      skip_build="NO"
+   fi
+
    if need_cmake_clean
    then
       cmake_clean
@@ -336,7 +402,7 @@ do_make()
    log_debug "do_make" "$*"
 
    (
-      exekutor cd build ;
+      exekutor cd "${BUILD_DIR}" ;
 
       if [ "${MULLE_TRACE}" = "YES" -o "${DUMP_ENVIRONMENT}" = "YES" ]
       then
@@ -518,28 +584,80 @@ prefix_cmake_flags()
 
 local_clean()
 {
+   log_debug "local_clean" "$*"
+
    log_fluff ":.:clean:.:"
 
    case "$1" in
       cmake)
+         cmake_cache_clean >&2
          cmake_clean >&2
          return
       ;;
 
 
       ""|*)
-         if [ -d "build" ]
+         if [ -d "${BUILD_DIR}" ]
          then
-            log_info "Deleting build"
-            exekutor rm -rf build
+            log_info "Deleting ${BUILD_DIR}"
+            exekutor rm -rf ${BUILD_DIR}
+         fi
+
+         if [ -d "tests/build" ]
+         then
+            log_info "Deleting tests/build"
+            exekutor rm -rf tests/build
+         fi
+         if [ -d "tests/include" ]
+         then
+            log_info "Deleting tests/include"
+            exekutor rm -rf tests/include
+         fi
+         if [ -d "tests/lib" ]
+         then
+            log_info "Deleting tests/lib"
+            exekutor rm -rf tests/lib
          fi
       ;;
    esac
 }
 
 
+cd_to_cmakelists_directory()
+{
+   local orgpwd
+   local old
+
+   orgpwd="$PWD"
+
+   while [ ! -f "CMakeLists.txt" ]
+   do
+      old="$PWD"
+
+      # adjust relative build dir name
+      case "${BUILD_DIR}" in
+         /*)
+         ;;
+
+         *)
+            BUILD_DIR="`basename "${PWD}"`/${BUILD_DIR}"
+         ;;
+      esac
+
+      exekutor cd ..
+
+      if [ "$PWD" = "${old}" ]
+      then
+         fail "There is no CMakeLists.txt here ($orgpwd), can't continue"
+      fi
+   done
+}
+
+
 local_mode()
 {
+   log_debug "local_mode" "$*"
+
    log_fluff ":.:local mode:.:"
 
    [ -z "${TAG}" ] || fail "-b option is not compatible with local mode."
@@ -552,23 +670,6 @@ local_mode()
 
       prefix_cmake_flags
    fi
-
-   local  orgpwd
-
-   orgpwd="$PWD"
-
-   while [ ! -f "CMakeLists.txt" ]
-   do
-      local old
-
-      old="$PWD"
-      cd ..
-
-      if [ "$PWD" = "${old}" ]
-      then
-         fail "There is no CMakeLists.txt here ($orgpwd), can't continue"
-      fi
-   done
 
    setup_cc_environment
    setup_make_environment
@@ -614,6 +715,10 @@ local_mode()
 
 xcode_mode()
 {
+   log_debug "xcode_mode" "$*"
+
+   log_fluff ":.:xcode mode:.:"
+
    setup_cc_environment
    setup_make_environment
 
@@ -660,6 +765,8 @@ xcode_mode()
 #
 url_mode()
 {
+   log_debug "url_mode" "$*"
+
    log_fluff ":.:URL mode:.:"
 
    [ -z "${DONT_BUILD}" ] || fail "-nb option is not compatible with URL install."
@@ -742,108 +849,10 @@ url_mode()
 }
 
 
-build_init()
-{
-   # look for mulle-bootstrap in the place where mulle-build is, they
-   # belong together
-
-   MULLE_BOOTSTRAP_EXE="`dirname -- "$0"`/mulle-bootstrap"
-   if [ ! -x "${MULLE_BOOTSTRAP_EXE}" ]
-   then
-      MULLE_BOOTSTRAP_EXE="`command -v mulle-bootstrap`"
-      if [ ! -x "${MULLE_BOOTSTRAP_EXE}" ]
-      then
-         echo "mulle-bootstrap not installed in $PATH. Can't continue!" >&2
-         exit 1
-      fi
-   fi
-
-   local libexecpath
-
-   libexecpath="`${MULLE_BOOTSTRAP_EXE} library-path`"
-   if [ -z "${libexecpath}" ]
-   then
-      echo "mulle-bootstrap not installed ? Can't continue" >&2
-      exit 1
-   fi
-
-   #
-   # shell export commands with minimal
-   # trap setup
-   #
-   case "${1}" in
-      version)
-         echo "${MULLE_EXECUTABLE_VERSION}"
-         exit 0
-      ;;
-
-      minimum-bootstrap-version)
-         echo "${MULLE_BOOTSTRAP_MIN_MAJOR}.${MULLE_BOOTSTRAP_MIN_MINOR}.0"
-         exit 0
-      ;;
-   esac
-
-
-   PATH="${libexecpath}:$PATH"
-   export PATH
-
-   if [ ! -z "${MULLE_BOOTSTRAP_LIBEXEC_TRACE}" ]
-   then
-      echo "PATH=$PATH" >&2
-   fi
-
-   . mulle-bootstrap-logging.sh
-   . mulle-bootstrap-local-environment.sh || fail "not loaded"
-   . mulle-bootstrap-functions.sh
-}
-
-
-run_install()
-{
-   URL="$1"
-
-   #
-   # when installing it doesn't make sense to skip it,
-   # which is the default
-   #
-   OPTION_SKIP_MULLE_BOOTSTRAP="NO"
-
-   case "${URL}" in
-      */*|*:*)
-         url_mode "$@"
-      ;;
-
-      ""|*)
-         if [ "${OPTION_XCODEPROJ}" = "YES" ]
-         then
-            xcode_mode "$@"
-         else
-            local_mode "$@"
-         fi
-      ;;
-   esac
-}
-
-
-run_build()
-{
-   if [ "${OPTION_XCODEPROJ}" = "YES" ]
-   then
-      xcode_mode "$@"
-   else
-      local_mode "$@"
-   fi
-}
-
-
-run_analyze()
-{
-   run_build "$@"
-}
-
-
 locate_tests()
 {
+   log_debug "locate_tests" "$*"
+
    local testdir
    local rootdir
 
@@ -907,8 +916,63 @@ locate_tests()
 }
 
 
+run_install()
+{
+   log_debug "run_install" "$*" "($PWD)"
+
+   URL="$1"
+
+   #
+   # when installing it doesn't make sense to skip it,
+   # which is the default
+   #
+
+   case "${URL}" in
+      */*|*:*)
+         url_mode "$@"
+      ;;
+
+      ""|*)
+         if [ "${OPTION_XCODEPROJ}" = "YES" ]
+         then
+            xcode_mode "$@"
+         else
+            cd_to_cmakelists_directory
+
+            cmake_cache_clean
+            local_mode "$@"
+         fi
+      ;;
+   esac
+}
+
+
+run_build()
+{
+   log_debug "run_build" "$*" "($PWD)"
+
+   if [ "${OPTION_XCODEPROJ}" = "YES" ]
+   then
+      xcode_mode "$@"
+   else
+      cd_to_cmakelists_directory
+      local_mode "$@"
+   fi
+}
+
+
+run_analyze()
+{
+   log_debug "run_analyze" "$*" "($PWD)"
+
+   run_build "$@"
+}
+
+
 run_test()
 {
+   log_debug "run_test" "$*"
+
    # check this first
    local testdir
    local userrel
@@ -928,15 +992,11 @@ run_test()
          TEST_PATH_PREFIX="${userrel}" eval_exekutor "./build-test.sh" "${BUILD_TEST_OPTIONS}" "$@"
       ) || exit 1
    else
-      log_fluff "No build-test.sh found."
-
-      if [ -f "CMakeLists.txt" ]
+      if [ -f "${testdir}/build-test.sh" ]
       then
-         log_fluff "CMakeLists.txt is present so build it."
-         OPTION_INSTALL="NO" local_mode "$@" || exit 1
-      else
-         log_fluff "CMakeLists.txt is not present. Nothing to build."
+         fail "build-test.sh is not executable"
       fi
+      log_verbose "No build-test.sh found"
    fi
 
    local cmdline
@@ -971,6 +1031,62 @@ run_test()
       exekutor cd "${testdir}"
       eval_exekutor "./run-test.sh" --path-prefix "'${userrel}'" "${TEST_OPTIONS}" "${cmdline}"
    ) || exit 1
+}
+
+
+build_init()
+{
+   # look for mulle-bootstrap in the place where mulle-build is, they
+   # belong together
+
+   MULLE_BOOTSTRAP_EXE="`dirname -- "$0"`/mulle-bootstrap"
+   if [ ! -x "${MULLE_BOOTSTRAP_EXE}" ]
+   then
+      MULLE_BOOTSTRAP_EXE="`command -v mulle-bootstrap`"
+      if [ ! -x "${MULLE_BOOTSTRAP_EXE}" ]
+      then
+         echo "mulle-bootstrap not installed in $PATH. Can't continue!" >&2
+         exit 1
+      fi
+   fi
+
+   local libexecpath
+
+   libexecpath="`${MULLE_BOOTSTRAP_EXE} library-path`"
+   if [ -z "${libexecpath}" ]
+   then
+      echo "mulle-bootstrap not installed ? Can't continue" >&2
+      exit 1
+   fi
+
+   #
+   # shell export commands with minimal
+   # trap setup
+   #
+   case "${1}" in
+      version)
+         echo "${MULLE_EXECUTABLE_VERSION}"
+         exit 0
+      ;;
+
+      minimum-bootstrap-version)
+         echo "${MULLE_BOOTSTRAP_MIN_MAJOR}.${MULLE_BOOTSTRAP_MIN_MINOR}.0"
+         exit 0
+      ;;
+   esac
+
+
+   PATH="${libexecpath}:$PATH"
+   export PATH
+
+   if [ ! -z "${MULLE_BOOTSTRAP_LIBEXEC_TRACE}" ]
+   then
+      echo "PATH=$PATH" >&2
+   fi
+
+   . mulle-bootstrap-logging.sh
+   . mulle-bootstrap-local-environment.sh || fail "not loaded"
+   . mulle-bootstrap-functions.sh
 }
 
 
@@ -1015,11 +1131,20 @@ main()
    local OPTION_LINK_XCODEPROJ="NO"
    local OPTION_FAST_TEST="NO"   # useful for homebrew, to skip slow tests
    local OPTION_SKIP_MULLE_BOOTSTRAP="YES"
+   local OPTION_AUTO_MIRROR="NO"
 
-   if [ "${MULLE_EXECUTABLE}" = "mulle-install" ]
-   then
-      OPTION_INSTALL="YES"
-   fi
+   #
+   # per command different defaults
+   #
+   case "${command}" in
+      "install")
+         log_fluff "Set different default values for install"
+
+         OPTION_INSTALL="YES"
+         OPTION_AUTO_MIRROR="YES"
+         OPTION_SKIP_MULLE_BOOTSTRAP="NO"
+      ;;
+   esac
 
    case "`uname`" in
       MINGW*)
@@ -1045,7 +1170,15 @@ main()
          continue
       fi
 
-      case "$1" in
+      case "$1"  in
+         --auto-mirror)
+            OPTION_AUTO_MIRROR="YES"
+         ;;
+
+         --no-auto-mirror)
+            OPTION_AUTO_MIRROR="NO"
+         ;;
+
          -b|--tag|--branch)
             [ $# -eq 1 ] && fail "missing argument to $1"
             shift
@@ -1089,6 +1222,7 @@ main()
             OPTION_BUILD_DEPENDENCIES="NO"
             OPTION_INSTALL_DEPENDENCIES="NO"
             OPTION_SKIP_MULLE_BOOTSTRAP="NO"
+            OPTION_AUTO_MIRROR="YES"
          ;;
 
          -h|--help)
@@ -1120,6 +1254,10 @@ main()
             OPTION_SKIP_MULLE_BOOTSTRAP="NO"
          ;;
 
+         -nbo|--no-bootstrap)
+            OPTION_SKIP_MULLE_BOOTSTRAP="YES"
+         ;;
+
          -ni|--no-install)
             OPTION_INSTALL="NO"
             OPTION_INSTALL_DEPENDENCIES="NO"
@@ -1131,6 +1269,20 @@ main()
 
          -nr|--no-remove)
             DONT_REMOVE="YES"
+         ;;
+
+         --build-dir)
+            [ $# -eq 1 ] && fail "missing argument to $1"
+            shift
+
+            BUILD_DIR="$1"
+         ;;
+
+         --xcode-build-dir)
+            [ $# -eq 1 ] && fail "missing argument to $1"
+            shift
+
+            XCODEBUILD_DIR="$1"
          ;;
 
          -p|--prefix)
@@ -1164,7 +1316,6 @@ main()
             locate_tests
             exit 0
          ;;
-
 
          --open-xcode)
             OPTION_OPEN_XCODE="YES"
@@ -1202,7 +1353,6 @@ main()
 
                -*)
                   BOOTSTRAP_FLAGS="`concat "${BOOTSTRAP_FLAGS}" "$1"`"
-                  TEST_OPTIONS="`concat "${TEST_OPTIONS}" "$1"`"
                   STATUS_OPTIONS="`concat "${STATUS_OPTIONS}" "$1"`"
                   WRAPPER_OPTIONS="`concat "${WRAPPER_OPTIONS}" "$1"`"
                ;;
